// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillsService.Infrastructure.Persistance;

#nullable disable

namespace SkillsService.Infrastructure.Migrations
{
    [DbContext(typeof(SkillsDbContext))]
    partial class SkillsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillsService.Domain.Entities.SkillCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SkillCatalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000000"),
                            Name = "Web Design"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000000"),
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000000"),
                            Name = "UI Design"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000000"),
                            Name = "UX Design"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000000"),
                            Name = "Mobile App Design"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-0000-0000-000000000000"),
                            Name = "Illustration"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-0000-0000-000000000000"),
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0008-0000-0000-000000000000"),
                            Name = "Branding"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0009-0000-0000-000000000000"),
                            Name = "Product Design"
                        });
                });

            modelBuilder.Entity("SkillsService.Domain.Entities.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillCatalogId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("SkillsService.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("SkillsService.Domain.Entities.SkillCatalog", "SkillCatalog")
                        .WithMany()
                        .HasForeignKey("SkillCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillCatalog");
                });
#pragma warning restore 612, 618
        }
    }
}
